### ISSUE TITLE
配置目录/root.zfile被忽略

### ISSUE THREAD

**Issue by xmu714** [xavier-niu/zfile-docker#1]
我按照说明映射了本机的/root/zfile/conf 到zfile的 /root/.zfile上面，也给了读写权限，但是db没有生成在那里面，而是在 /root/.zfile-new里面。这样每次更新重新部署数据会丢失。

**Comment by justxuewei** [comment]
是的 我发现这个问题了 马上更新

**Comment by justxuewei** [comment]
已更新 请尝试最新版本

**Comment by xmu714** [comment]
> 已更新 请尝试最新版本

现在是直接映射 /root/.zfile-new吗

**Comment by justxuewei** [comment]
是的，可以看一下github的readme

**Comment by xmu714** [comment]
感谢，刚才pull最新镜像已修复。
